Repository fylgja/fylgja, pull requests merged in 2025-03, with the labels that each got.

#271 ADD: aria-disabled to btn's
  base/src/buttons/_index.scss
Labels: enhancement

#282 FIX: flow type in auto-grid
  utilities/src/utils/auto-grid.scss
Labels: Bug

#284 Add missing utilities
  utilities/src/utils/align.scss
  utilities/src/utils/display.scss
  utilities/src/utils/flex.scss
Labels: Enhancement, New Feature
